# Site settings
title: xuxanwan's Blog
email: xuxanwan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Life isn't about finding yourself. Life is about creating yourself. 
baseurl: "/myblog" # the subpath of your site, e.g. /blog/
url: "http://xuxanwan.github.io" # the base hostname & protocol for your site
twitter_username: xPleasure5
github_username:  xuxanwan

# Build settings
markdown: kramdown


#kramdown:
#  auto_ids: true
#  footnote_nr: 1
#  entity_output: as_char
#  toc_levels: 1..6
#  use_coderay: false
#
#  coderay:
#    coderay_line_numbers: nil
#    coderay_line_numbers_start: 1
#    coderay_tab_width: 4
#    coderay_bold_every: 10
#    coderay_css: class